# Configuration for https://github.com/wei/pull
version: "1"
rules:
  - base: develop
    upstream: com-pas:develop
    mergeMethod: hardreset
    mergeUnstable: true  # Merge PRs even if their GitHub Actions workflows are failing
